### ISSUE TITLE
Cardiac markers data 1999-2004

### ISSUE THREAD

**Issue by ljacks-stats** [cran/nhanesA#2]
Hi, I was looking to use cardiac troponin & NTpro-BNP data from the 1999-2004 cohorts which is available in the NHANES lab data but does not seem to be available in this package?

**Comment by cjendres1** [comment]
Please let me know which specific tables and/or variables you are looking for. If the tables are available on the NHANES website then nhanesA should be  able to download them.
To list available tables you can use:
`nhanesTables('LAB', 1999)`

Alternatively, you can use nhanesSearch to find tables where the start year is 1999 and end year is 2004.
`nhanes_vars <- nhanesSearch("*", data_group = 'LAB', ystop=2004) %>% filter(Begin.Year == 1999 & EndYear == 2004)`

If you want just table names:
`unique(nhanes_vars$Data.File.Name)`

Then download an individual file with:
`ssbnp_a <- nhanes("SSBNP_A")`

Please let me know if that is what you wanted.
Thanks for using nhanesA!

Chris

**Comment by laurel-jackson** [comment]
Hi! I was using a similar command as your first command below to look for this data in the 1999 lab tables: 
`nhanesTables('LAB', 1999)`

However I noticed that the BNP/troponin tables do not show up in this first list (1999 only), but then when using **nhanesSearch** it does show up (1999-2004). Is this because the data was collected after the original 1999 lab tables were released, and is stored in a separate batch?

Thank you for the help! 

In any case, the last line to download the individual file is what I was looking for, I just could not find it with the first type of search and was wondering if it was not yet updated in your package.

**Comment by ljacks-stats** [comment]
Hi! I was using a similar command as your first command below to look for this data in the 1999 lab tables:
`nhanesTables('LAB', 1999)
`
However I noticed that the BNP/troponin tables do not show up in this first list (1999 only), but then when using **nhanesSearch** it does show up (1999-2004). Is this because the data was collected after the original 1999 lab tables were released, and is stored in a separate batch?

Thank you for the help!

In any case, the last line to download the individual file is what I was looking for, I just could not find it with the first type of search and was wondering if it was not yet updated in your package.

**Comment by cjendres1** [comment]
The NHANES website has some inconsistencies, especially with data from the first several years. nhanesTables and nhanesSearch are scraping different web pages. For the vast majority of cases, the data on those pages are consistent. However, for the specific data you're looking for it is not.  In this case, nhanesSearch finds the table but nhanesTables does not. It seems to only impact the following tables:
 "SSANA_A"  "SSUCSH_A" "SSCMVG_A" "SSANA2_A" "SSDFS_A"  "SSCARD_A" "SSBNP_A" "SSTROP_A"

**Comment by ljacks-stats** [comment]
Thank you for the clarification!
